In [1]:
import numpy as np
import pandas as pd

## Load dataset

In [32]:
csv_original = 'DataSetNike.csv'
original_dataset = pd.read_csv(csv_original, encoding='latin-1', low_memory=False)
print original_dataset

           Store            Date  No_Tran           UPC    Material Size  \
0       TIENDA 1   9/1/2017 0:00    45372  9.120108e+10  146124-VQD    L
1       TIENDA 1   9/1/2017 0:00    52913  9.120120e+10  662009-ZQH    L
2       TIENDA 1   9/1/2017 0:00    58648  9.120137e+10  990552-HCP  5.5
3       TIENDA 1   9/1/2017 0:00    58659  9.120137e+10  990552-HCP  5.5
4       TIENDA 1   9/1/2017 0:00    58658  9.120137e+10  990552-HCP  5.5
5       TIENDA 1   9/1/2017 0:00    58610  9.120137e+10  990552-HCP  6.5
6       TIENDA 1   9/1/2017 0:00    52924  9.120137e+10  990552-HCP  6.5
7       TIENDA 1   9/1/2017 0:00    52846  9.120137e+10  990552-HCP  7.5
8       TIENDA 1   9/1/2017 0:00    52846  9.120141e+10  662014-IQQ    M
9       TIENDA 1   9/1/2017 0:00    58690  9.120150e+10  327277-NNV    S
10      TIENDA 1   9/1/2017 0:00    45397  9.120249e+10  659994-MAU    7
11      TIENDA 1   9/1/2017 0:00    52970  9.120249e+10  659994-MAU    7
12      TIENDA 1   9/1/2017 0:00    45499  9.120254e+10  212577-XEF   XS
13      TIENDA 1   9/1/2017 0:00    58659  9.120254e+10  212577-XEF    S
14      TIENDA 1   9/1/2017 0:00    58648  9.120254e+10  212577-XEF    S
15      TIENDA 1   9/1/2017 0:00    45523  9.120254e+10  212577-XEF    S
16      TIENDA 1   9/1/2017 0:00    58658  9.120254e+10  212577-XEF    S
17      TIENDA 1   9/1/2017 0:00    52846  9.120254e+10  212577-XEF    M
18      TIENDA 1   9/1/2017 0:00    52937  9.120254e+10  212577-XEF    M
19      TIENDA 1   9/1/2017 0:00    58659  9.120254e+10  212577-XEF    L
20      TIENDA 1   9/1/2017 0:00    58648  9.120254e+10  212577-XEF    L
21      TIENDA 1   9/1/2017 0:00    58658  9.120254e+10  212577-XEF    L
22      TIENDA 1   9/1/2017 0:00    45470  9.120297e+10  163605-LET    9
23      TIENDA 1   9/1/2017 0:00    45417  9.120321e+10  660689-PGX    7
24      TIENDA 1   9/1/2017 0:00    45391  9.120321e+10  660689-PGX    7
25      TIENDA 1   9/1/2017 0:00    45418  9.120321e+10  660689-PGX    8
26      TIENDA 1   9/1/2017 0:00    45390  9.120321e+10  760862-QGY    9
27      TIENDA 1   9/1/2017 0:00    52954  9.120365e+10  163518-KCS  6.5
28      TIENDA 1   9/1/2017 0:00    45461  9.120365e+10  163518-KCS    7
29      TIENDA 1   9/1/2017 0:00    52931  9.120365e+10  163518-KCS    8
...          ...             ...      ...           ...         ...  ...
263657  TIENDA 1  9/30/2018 0:00    26144  8.880000e+11  661984-GQO    S
263658  TIENDA 1  9/30/2018 0:00    26197  8.880000e+11  661984-GQO    M
263659  TIENDA 1  9/30/2018 0:00     3142  8.880000e+11  661984-GQO    L
263660  TIENDA 1  9/30/2018 0:00      689  8.880000e+11  762578-QRY   XL
263661  TIENDA 1  9/30/2018 0:00    19279  8.880000e+11  215577-STA   XL
263662  TIENDA 1  9/30/2018 0:00    19263  8.880000e+11  454287-YNG    S
263663  TIENDA 1  9/30/2018 0:00    26200  8.880000e+11  994341-ATI    M
263664  TIENDA 1  9/30/2018 0:00    95006  8.880000e+11  994341-ATI    M
263665  TIENDA 1  9/30/2018 0:00    95017  8.880000e+11  146194-BTJ    L
263666  TIENDA 1  9/30/2018 0:00    26174  8.880000e+11  573867-VWD    S
263667  TIENDA 1  9/30/2018 0:00    95018  8.880000e+11  573867-VWD   XL
263668  TIENDA 1  9/30/2018 0:00    95075  8.880000e+11  572999-XRF    L
263669  TIENDA 1  9/30/2018 0:00    94928  8.880000e+11  662089-NRV    S
263670  TIENDA 1  9/30/2018 0:00    19329  8.880000e+11  215145-ARI    M
263671  TIENDA 1  9/30/2018 0:00    19305  8.880000e+11  215145-ARI    L
263672  TIENDA 1  9/30/2018 0:00    95080  8.880000e+11  662114-GRO    S
263673  TIENDA 1  9/30/2018 0:00     3111  8.880000e+11  662114-GRO    S
263674  TIENDA 1  9/30/2018 0:00    19309  8.880000e+11  573048-IRQ    S
263675  TIENDA 1  9/30/2018 0:00    95070  8.880000e+11  573048-IRQ    M
263676  TIENDA 1  9/30/2018 0:00     3111  8.880000e+11  573048-IRQ    M
263677  TIENDA 1  9/30/2018 0:00    19281  8.880000e+11  573048-IRQ    L
263678  TIENDA 1  9/30/2018 0:00    26133  8.880000e+11  573048-IRQ    L
263679  TIENDA 1  9/30/2018 0:00    19302  8.880000e+11  573202-YSG    M
263680  TIENDA 1  9/30/2018 0:00    26111  8.880000e+11  573657-LUT    M
263681  TIENDA 1  9/30/2018 0:00    19384  8.880000e+11  662699-TWB    7
263682  TIENDA 1  9/30/2018 0:00     3142  8.880000e+11  662829-TXB    S
263683  TIENDA 1  9/30/2018 0:00    26164  8.890000e+11  164064-KKS    S
263684  TIENDA 1  9/30/2018 0:00    95090  8.890000e+11  327345-HOP   XL
263685  TIENDA 1  9/30/2018 0:00     3075  8.890000e+11  164436-IOQ    M
263686  TIENDA 1  9/30/2018 0:00    26174  8.890000e+11  164436-IOQ    M

        Division  Global Category  Gender  Public Price  Units  \
0        APPAREL  NIKE SPORTSWEAR    MENS         349.0      1
1        APPAREL  NIKE SPORTSWEAR    MENS         349.0      1
2       FOOTWEAR  NIKE SPORTSWEAR  WOMENS         999.0      1
3       FOOTWEAR  NIKE SPORTSWEAR  WOMENS         999.0      1
4       FOOTWEAR  NIKE SPORTSWEAR  WOMENS        -599.4     -1
5       FOOTWEAR  NIKE SPORTSWEAR  WOMENS         999.0      1
6       FOOTWEAR  NIKE SPORTSWEAR  WOMENS         999.0      1
7       FOOTWEAR  NIKE SPORTSWEAR  WOMENS         999.0      1
8        APPAREL  NIKE SPORTSWEAR  WOMENS         249.0      1
9        APPAREL  NIKE SPORTSWEAR  WOMENS         449.0      1
10      FOOTWEAR  NIKE SPORTSWEAR  WOMENS        -899.4     -1
11      FOOTWEAR  NIKE SPORTSWEAR  WOMENS        1499.0      1
12       APPAREL  NIKE SPORTSWEAR  WOMENS         699.0      1
13       APPAREL  NIKE SPORTSWEAR  WOMENS        1398.0      2
14       APPAREL  NIKE SPORTSWEAR  WOMENS        1398.0      2
15       APPAREL  NIKE SPORTSWEAR  WOMENS         699.0      1
16       APPAREL  NIKE SPORTSWEAR  WOMENS        -838.8     -2
17       APPAREL  NIKE SPORTSWEAR  WOMENS         699.0      1
18       APPAREL  NIKE SPORTSWEAR  WOMENS         699.0      1
19       APPAREL  NIKE SPORTSWEAR  WOMENS         699.0      1
20       APPAREL  NIKE SPORTSWEAR  WOMENS         699.0      1
21       APPAREL  NIKE SPORTSWEAR  WOMENS        -419.4     -1
22      FOOTWEAR  FOOTBALL/SOCCER    MENS        1199.0      1
23      FOOTWEAR  NIKE SPORTSWEAR    MENS        -999.5     -1
24      FOOTWEAR  NIKE SPORTSWEAR    MENS        1999.0      1
25      FOOTWEAR  NIKE SPORTSWEAR    MENS         999.5      1
26      FOOTWEAR  NIKE SPORTSWEAR    MENS       -1199.4     -1
27      FOOTWEAR  NIKE SPORTSWEAR  WOMENS         849.0      1
28      FOOTWEAR  NIKE SPORTSWEAR  WOMENS         849.0      1
29      FOOTWEAR  NIKE SPORTSWEAR  WOMENS         849.0      1
...          ...              ...     ...           ...    ...
263657   APPAREL  NIKE SPORTSWEAR    MENS         599.0      1
263658   APPAREL  NIKE SPORTSWEAR    MENS         599.0      1
263659   APPAREL  NIKE SPORTSWEAR    MENS         599.0      1
263660   APPAREL  NIKE SPORTSWEAR    MENS         649.0      1
263661   APPAREL  NIKE SPORTSWEAR    MENS         549.0      1
263662   APPAREL          RUNNING    MENS        1099.0      1
263663   APPAREL          RUNNING    MENS         549.0      1
263664   APPAREL          RUNNING    MENS         549.0      1
263665   APPAREL          RUNNING    MENS         599.0      1
263666   APPAREL          RUNNING    MENS         799.0      1
263667   APPAREL          RUNNING    MENS         799.0      1
263668   APPAREL          RUNNING  WOMENS         899.0      1
263669   APPAREL          RUNNING    MENS         799.0      1
263670   APPAREL          RUNNING    MENS         599.0      1
263671   APPAREL          RUNNING    MENS         599.0      1
263672   APPAREL          RUNNING    MENS         899.0      1
263673   APPAREL          RUNNING    MENS         899.0      1
263674   APPAREL          RUNNING    MENS         749.0      1
263675   APPAREL          RUNNING    MENS         749.0      1
263676   APPAREL          RUNNING    MENS         749.0      1
263677   APPAREL          RUNNING    MENS         749.0      1
263678   APPAREL          RUNNING    MENS         749.0      1
263679   APPAREL          RUNNING  WOMENS         649.0      1
263680   APPAREL          RUNNING  WOMENS         799.0      1
263681  FOOTWEAR  NIKE SPORTSWEAR    MENS        1799.0      1
263682   APPAREL  FOOTBALL/SOCCER    MENS        1099.0      1
263683   APPAREL  NIKE SPORTSWEAR  WOMENS        2699.0      1
263684   APPAREL       BASKETBALL    MENS         379.0      1
263685   APPAREL       BASKETBALL    MENS         379.0      1
263686   APPAREL       BASKETBALL    MENS         379.0      1

        Sale Price Wo tax         Tax  Sale Price  Discount  \
0              150.431035   24.068966      174.50    174.50
1              210.603448   33.696552      244.30    104.70
2              516.724138   82.675862      599.40    399.60
3              430.603448   68.896552      499.50    499.50
4             -516.724138  -82.675862     -599.40      0.00
5              861.206897  137.793103      999.00      0.00
6              482.275862   77.164138      559.44    439.56
7              301.422414   48.227586      349.65    649.35
8               75.129310   12.020690       87.15    161.85
9              309.655172   49.544828      359.20     89.80
10            -775.344828 -124.055172     -899.40      0.00
11            1033.793103  165.406897     1199.20    299.80
12             301.293104   48.206897      349.50    349.50
13             602.586207   96.413793      699.00    699.00
14             723.103448  115.696552      838.80    559.20
15             342.258621   54.761379      397.02    301.98
16            -723.103448 -115.696552     -838.80      0.00
17             210.905172   33.744828      244.65    454.35
18             482.068966   77.131034      559.20    139.80
19             301.293104   48.206897      349.50    349.50
20             361.551724   57.848276      419.40    279.60
21            -361.551724  -57.848276     -419.40      0.00
22             413.448276   66.151724      479.60    719.40
23            -861.637931 -137.862069     -999.50      0.00
24             861.637931  137.862069      999.50    999.50
25             861.637931  137.862069      999.50      0.00
26           -1033.965517 -165.434483    -1199.40      0.00
27             731.896552  117.103448      849.00      0.00
28             365.948276   58.551724      424.50    424.50
29             585.517241   93.682759      679.20    169.80
...                   ...         ...         ...       ...
263657         289.172414   46.267586      335.44    263.56
263658         289.172414   46.267586      335.44    263.56
263659         289.172414   46.267586      335.44    263.56
263660         391.637931   62.662069      454.30    194.70
263661         331.293103   53.006897      384.30    164.70
263662         606.344828   97.015172      703.36    395.64
263663         331.293103   53.006897      384.30    164.70
263664         331.293103   53.006897      384.30    164.70
263665         464.741379   74.358621      539.10     59.90
263666         385.724138   61.715862      447.44    351.56
263667         385.724138   61.715862      447.44    351.56
263668         542.500000   86.800000      629.30    269.70
263669         482.155172   77.144828      559.30    239.70
263670         361.465517   57.834483      419.30    179.70
263671         361.465517   57.834483      419.30    179.70
263672         542.500000   86.800000      629.30    269.70
263673         542.500000   86.800000      629.30    269.70
263674         451.982759   72.317241      524.30    224.70
263675         451.982759   72.317241      524.30    224.70
263676         451.982759   72.317241      524.30    224.70
263677         451.982759   72.317241      524.30    224.70
263678         451.982759   72.317241      524.30    224.70
263679         391.637931   62.662069      454.30    194.70
263680         385.724138   61.715862      447.44    351.56
263681         868.482759  138.957241     1007.44    791.56
263682         371.379310   59.420690      430.80    668.20
263683        1302.965517  208.474483     1511.44   1187.56
263684         228.706897   36.593103      265.30    113.70
263685         228.706897   36.593103      265.30    113.70
263686         228.706897   36.593103      265.30    113.70

                                 Promo            Sales Type   Emp No  \
0       TIERED PROMOTION VALUE 50P OFF          4 - PROMOTION     NaN
1       TIERED PROMOTION VALUE 30P OFF          4 - PROMOTION     NaN
2       TIERED PROMOTION VALUE 40P OFF          4 - PROMOTION     NaN
3       TIERED PROMOTION VALUE 50P OFF          4 - PROMOTION     NaN
4                                                 2 - RETURNS     NaN
5                                                  1 - NORMAL     NaN
6       TIERED PROMOTION VALUE 20P OFF  5 - EMPLOYEE DISCOUNT  338083
7       TIERED PROMOTION VALUE 50P OFF  5 - EMPLOYEE DISCOUNT  185634
8       TIERED PROMOTION VALUE 50P OFF  5 - EMPLOYEE DISCOUNT  185634
9       TIERED PROMOTION VALUE 20P OFF          4 - PROMOTION     NaN
10                                                2 - RETURNS     NaN
11      TIERED PROMOTION VALUE 20P OFF          4 - PROMOTION     NaN
12      TIERED PROMOTION VALUE 50P OFF          4 - PROMOTION     NaN
13      TIERED PROMOTION VALUE 50P OFF          4 - PROMOTION     NaN
14      TIERED PROMOTION VALUE 40P OFF          4 - PROMOTION     NaN
15      TIERED PROMOTION VALUE 40P OFF          4 - PROMOTION     NaN
16                                                2 - RETURNS     NaN
17      TIERED PROMOTION VALUE 50P OFF  5 - EMPLOYEE DISCOUNT  185634
18      TIERED PROMOTION VALUE 20P OFF          4 - PROMOTION     NaN
19      TIERED PROMOTION VALUE 50P OFF          4 - PROMOTION     NaN
20      TIERED PROMOTION VALUE 40P OFF          4 - PROMOTION     NaN
21                                                2 - RETURNS     NaN
22      TIERED PROMOTION VALUE 50P OFF          4 - PROMOTION     NaN
23                                                2 - RETURNS     NaN
24      TIERED PROMOTION VALUE 50P OFF          4 - PROMOTION     NaN
25                                                 1 - NORMAL     NaN
26                                                2 - RETURNS     NaN
27                                                 1 - NORMAL     NaN
28      TIERED PROMOTION VALUE 50P OFF          4 - PROMOTION     NaN
29      TIERED PROMOTION VALUE 20P OFF          4 - PROMOTION     NaN
...                                ...                    ...     ...
263657           Store Level Promotion          4 - PROMOTION     NaN
263658           Store Level Promotion          4 - PROMOTION     NaN
263659           Store Level Promotion          4 - PROMOTION     NaN
263660                  MX NFS 30P OFF          4 - PROMOTION     NaN
263661                  MX NFS 30P OFF          4 - PROMOTION     NaN
263662           Store Level Promotion          4 - PROMOTION     NaN
263663                  MX NFS 30P OFF          4 - PROMOTION     NaN
263664                  MX NFS 30P OFF          4 - PROMOTION     NaN
263665                  MX NFS 10P OFF          4 - PROMOTION     NaN
263666           Store Level Promotion          4 - PROMOTION     NaN
263667           Store Level Promotion          4 - PROMOTION     NaN
263668                  MX NFS 30P OFF          4 - PROMOTION     NaN
263669                  MX NFS 30P OFF          4 - PROMOTION     NaN
263670                  MX NFS 30P OFF          4 - PROMOTION     NaN
263671                  MX NFS 30P OFF          4 - PROMOTION     NaN
263672                  MX NFS 30P OFF          4 - PROMOTION     NaN
263673                  MX NFS 30P OFF          4 - PROMOTION     NaN
263674                  MX NFS 30P OFF          4 - PROMOTION     NaN
263675                  MX NFS 30P OFF          4 - PROMOTION     NaN
263676                  MX NFS 30P OFF          4 - PROMOTION     NaN
263677                  MX NFS 30P OFF          4 - PROMOTION     NaN
263678                  MX NFS 30P OFF          4 - PROMOTION     NaN
263679                  MX NFS 30P OFF          4 - PROMOTION     NaN
263680           Store Level Promotion          4 - PROMOTION     NaN
263681           Store Level Promotion          4 - PROMOTION     NaN
263682           Store Level Promotion          4 - PROMOTION     NaN
263683           Store Level Promotion          4 - PROMOTION     NaN
263684                  MX NFS 30P OFF          4 - PROMOTION     NaN
263685                  MX NFS 30P OFF          4 - PROMOTION     NaN
263686                  MX NFS 30P OFF          4 - PROMOTION     NaN

        Sales Man     TTL Cost
0          357477   106.418005
1          274702   106.418005
2          340843   299.220506
3          340843   299.220506
4          340843  -299.220506
5          340843   299.220506
6          274702   299.220506
7          274702   299.220506
8          274702    98.535730
9          340843   171.137170
10         357477  -582.064528
11         274702   582.064528
12         357477   287.652064
13         340843   575.304129
14         340843   575.304129
15         357477   287.652064
16         340843  -575.304129
17         274702   287.652064
18         274702   287.652064
19         340843   287.652064
20         340843   287.652064
21         340843  -287.652064
22         357477   716.165201
23         357477 -1020.470576
24         357477  1020.470576
25         357477  1020.470576
26         357477 -1015.662533
27         274702   359.554153
28         357477   359.554153
29         274702   359.554153
...           ...          ...
263657     362045   241.582276
263658     409947   241.582276
263659     269303   241.582276
263660     351388   306.476279
263661     312652   215.196322
263662     312652   389.189178
263663     409947   211.495587
263664     340843   211.495587
263665     318683   169.549059
263666     362045   306.476279
263667     318683   306.476279
263668     340843   357.164702
263669     340843   313.309527
263670     312652   230.013835
263671     312652   230.013835
263672     340843   297.297289
263673     269303   297.297289
263674     312652   298.331746
263675     340843   298.331746
263676     269303   298.331746
263677     312652   298.331746
263678     362045   298.331746
263679     312652   272.703423
263680     362045   219.348722
263681     312652   541.531273
263682     269303   475.442545
263683     362045  1379.849891
263684     340843   561.011130
263685     269303   143.935306
263686     362045   143.935306

[263687 rows x 20 columns]

## Select columns

In [34]:
filtered_columns = original_dataset[['Material','Date', 'Units']]
print filtered_columns

          Material            Date  Units
0       146124-VQD   9/1/2017 0:00      1
1       662009-ZQH   9/1/2017 0:00      1
2       990552-HCP   9/1/2017 0:00      1
3       990552-HCP   9/1/2017 0:00      1
4       990552-HCP   9/1/2017 0:00     -1
5       990552-HCP   9/1/2017 0:00      1
6       990552-HCP   9/1/2017 0:00      1
7       990552-HCP   9/1/2017 0:00      1
8       662014-IQQ   9/1/2017 0:00      1
9       327277-NNV   9/1/2017 0:00      1
10      659994-MAU   9/1/2017 0:00     -1
11      659994-MAU   9/1/2017 0:00      1
12      212577-XEF   9/1/2017 0:00      1
13      212577-XEF   9/1/2017 0:00      2
14      212577-XEF   9/1/2017 0:00      2
15      212577-XEF   9/1/2017 0:00      1
16      212577-XEF   9/1/2017 0:00     -2
17      212577-XEF   9/1/2017 0:00      1
18      212577-XEF   9/1/2017 0:00      1
19      212577-XEF   9/1/2017 0:00      1
20      212577-XEF   9/1/2017 0:00      1
21      212577-XEF   9/1/2017 0:00     -1
22      163605-LET   9/1/2017 0:00      1
23      660689-PGX   9/1/2017 0:00     -1
24      660689-PGX   9/1/2017 0:00      1
25      660689-PGX   9/1/2017 0:00      1
26      760862-QGY   9/1/2017 0:00     -1
27      163518-KCS   9/1/2017 0:00      1
28      163518-KCS   9/1/2017 0:00      1
29      163518-KCS   9/1/2017 0:00      1
...            ...             ...    ...
263657  661984-GQO  9/30/2018 0:00      1
263658  661984-GQO  9/30/2018 0:00      1
263659  661984-GQO  9/30/2018 0:00      1
263660  762578-QRY  9/30/2018 0:00      1
263661  215577-STA  9/30/2018 0:00      1
263662  454287-YNG  9/30/2018 0:00      1
263663  994341-ATI  9/30/2018 0:00      1
263664  994341-ATI  9/30/2018 0:00      1
263665  146194-BTJ  9/30/2018 0:00      1
263666  573867-VWD  9/30/2018 0:00      1
263667  573867-VWD  9/30/2018 0:00      1
263668  572999-XRF  9/30/2018 0:00      1
263669  662089-NRV  9/30/2018 0:00      1
263670  215145-ARI  9/30/2018 0:00      1
263671  215145-ARI  9/30/2018 0:00      1
263672  662114-GRO  9/30/2018 0:00      1
263673  662114-GRO  9/30/2018 0:00      1
263674  573048-IRQ  9/30/2018 0:00      1
263675  573048-IRQ  9/30/2018 0:00      1
263676  573048-IRQ  9/30/2018 0:00      1
263677  573048-IRQ  9/30/2018 0:00      1
263678  573048-IRQ  9/30/2018 0:00      1
263679  573202-YSG  9/30/2018 0:00      1
263680  573657-LUT  9/30/2018 0:00      1
263681  662699-TWB  9/30/2018 0:00      1
263682  662829-TXB  9/30/2018 0:00      1
263683  164064-KKS  9/30/2018 0:00      1
263684  327345-HOP  9/30/2018 0:00      1
263685  164436-IOQ  9/30/2018 0:00      1
263686  164436-IOQ  9/30/2018 0:00      1

[263687 rows x 3 columns]

## Column Material - Delete rows with empty cells

In [41]:
filtered_void_rows = filtered_columns[~filtered_columns.Material.isnull()]
print filtered_void_rows

          Material            Date  Units
0       146124-VQD   9/1/2017 0:00      1
1       662009-ZQH   9/1/2017 0:00      1
2       990552-HCP   9/1/2017 0:00      1
3       990552-HCP   9/1/2017 0:00      1
4       990552-HCP   9/1/2017 0:00     -1
5       990552-HCP   9/1/2017 0:00      1
6       990552-HCP   9/1/2017 0:00      1
7       990552-HCP   9/1/2017 0:00      1
8       662014-IQQ   9/1/2017 0:00      1
9       327277-NNV   9/1/2017 0:00      1
10      659994-MAU   9/1/2017 0:00     -1
11      659994-MAU   9/1/2017 0:00      1
12      212577-XEF   9/1/2017 0:00      1
13      212577-XEF   9/1/2017 0:00      2
14      212577-XEF   9/1/2017 0:00      2
15      212577-XEF   9/1/2017 0:00      1
16      212577-XEF   9/1/2017 0:00     -2
17      212577-XEF   9/1/2017 0:00      1
18      212577-XEF   9/1/2017 0:00      1
19      212577-XEF   9/1/2017 0:00      1
20      212577-XEF   9/1/2017 0:00      1
21      212577-XEF   9/1/2017 0:00     -1
22      163605-LET   9/1/2017 0:00      1
23      660689-PGX   9/1/2017 0:00     -1
24      660689-PGX   9/1/2017 0:00      1
25      660689-PGX   9/1/2017 0:00      1
26      760862-QGY   9/1/2017 0:00     -1
27      163518-KCS   9/1/2017 0:00      1
28      163518-KCS   9/1/2017 0:00      1
29      163518-KCS   9/1/2017 0:00      1
...            ...             ...    ...
263657  661984-GQO  9/30/2018 0:00      1
263658  661984-GQO  9/30/2018 0:00      1
263659  661984-GQO  9/30/2018 0:00      1
263660  762578-QRY  9/30/2018 0:00      1
263661  215577-STA  9/30/2018 0:00      1
263662  454287-YNG  9/30/2018 0:00      1
263663  994341-ATI  9/30/2018 0:00      1
263664  994341-ATI  9/30/2018 0:00      1
263665  146194-BTJ  9/30/2018 0:00      1
263666  573867-VWD  9/30/2018 0:00      1
263667  573867-VWD  9/30/2018 0:00      1
263668  572999-XRF  9/30/2018 0:00      1
263669  662089-NRV  9/30/2018 0:00      1
263670  215145-ARI  9/30/2018 0:00      1
263671  215145-ARI  9/30/2018 0:00      1
263672  662114-GRO  9/30/2018 0:00      1
263673  662114-GRO  9/30/2018 0:00      1
263674  573048-IRQ  9/30/2018 0:00      1
263675  573048-IRQ  9/30/2018 0:00      1
263676  573048-IRQ  9/30/2018 0:00      1
263677  573048-IRQ  9/30/2018 0:00      1
263678  573048-IRQ  9/30/2018 0:00      1
263679  573202-YSG  9/30/2018 0:00      1
263680  573657-LUT  9/30/2018 0:00      1
263681  662699-TWB  9/30/2018 0:00      1
263682  662829-TXB  9/30/2018 0:00      1
263683  164064-KKS  9/30/2018 0:00      1
263684  327345-HOP  9/30/2018 0:00      1
263685  164436-IOQ  9/30/2018 0:00      1
263686  164436-IOQ  9/30/2018 0:00      1

[263459 rows x 3 columns]

## Shapes

In [54]:
print "Original Dataset: ", dataset_original.shape
fvr = filtered_void_rows.shape
print "Filtered void rows:", fvr
fc = filtered_columns.shape
print "Filtered columns: ", fc
print "Rows difference: ", fc[0] - fvr[0]

Original Dataset:  (263687, 20)
Filtered void rows: (263459, 3)
Filtered columns:  (263687, 3)
Rows difference:  228

## Column Units - Delete rows with cells less than 1 . 5561

In [55]:
filtered_less_rows = filtered_void_rows[lambda d: filtered_void_rows.Units < 1.5561]
print filtered_less_rows

          Material            Date  Units
0       146124-VQD   9/1/2017 0:00      1
1       662009-ZQH   9/1/2017 0:00      1
2       990552-HCP   9/1/2017 0:00      1
3       990552-HCP   9/1/2017 0:00      1
4       990552-HCP   9/1/2017 0:00     -1
5       990552-HCP   9/1/2017 0:00      1
6       990552-HCP   9/1/2017 0:00      1
7       990552-HCP   9/1/2017 0:00      1
8       662014-IQQ   9/1/2017 0:00      1
9       327277-NNV   9/1/2017 0:00      1
10      659994-MAU   9/1/2017 0:00     -1
11      659994-MAU   9/1/2017 0:00      1
12      212577-XEF   9/1/2017 0:00      1
15      212577-XEF   9/1/2017 0:00      1
16      212577-XEF   9/1/2017 0:00     -2
17      212577-XEF   9/1/2017 0:00      1
18      212577-XEF   9/1/2017 0:00      1
19      212577-XEF   9/1/2017 0:00      1
20      212577-XEF   9/1/2017 0:00      1
21      212577-XEF   9/1/2017 0:00     -1
22      163605-LET   9/1/2017 0:00      1
23      660689-PGX   9/1/2017 0:00     -1
24      660689-PGX   9/1/2017 0:00      1
25      660689-PGX   9/1/2017 0:00      1
26      760862-QGY   9/1/2017 0:00     -1
27      163518-KCS   9/1/2017 0:00      1
28      163518-KCS   9/1/2017 0:00      1
29      163518-KCS   9/1/2017 0:00      1
30      163518-KCS   9/1/2017 0:00      1
31      453195-LCT   9/1/2017 0:00      1
...            ...             ...    ...
263657  661984-GQO  9/30/2018 0:00      1
263658  661984-GQO  9/30/2018 0:00      1
263659  661984-GQO  9/30/2018 0:00      1
263660  762578-QRY  9/30/2018 0:00      1
263661  215577-STA  9/30/2018 0:00      1
263662  454287-YNG  9/30/2018 0:00      1
263663  994341-ATI  9/30/2018 0:00      1
263664  994341-ATI  9/30/2018 0:00      1
263665  146194-BTJ  9/30/2018 0:00      1
263666  573867-VWD  9/30/2018 0:00      1
263667  573867-VWD  9/30/2018 0:00      1
263668  572999-XRF  9/30/2018 0:00      1
263669  662089-NRV  9/30/2018 0:00      1
263670  215145-ARI  9/30/2018 0:00      1
263671  215145-ARI  9/30/2018 0:00      1
263672  662114-GRO  9/30/2018 0:00      1
263673  662114-GRO  9/30/2018 0:00      1
263674  573048-IRQ  9/30/2018 0:00      1
263675  573048-IRQ  9/30/2018 0:00      1
263676  573048-IRQ  9/30/2018 0:00      1
263677  573048-IRQ  9/30/2018 0:00      1
263678  573048-IRQ  9/30/2018 0:00      1
263679  573202-YSG  9/30/2018 0:00      1
263680  573657-LUT  9/30/2018 0:00      1
263681  662699-TWB  9/30/2018 0:00      1
263682  662829-TXB  9/30/2018 0:00      1
263683  164064-KKS  9/30/2018 0:00      1
263684  327345-HOP  9/30/2018 0:00      1
263685  164436-IOQ  9/30/2018 0:00      1
263686  164436-IOQ  9/30/2018 0:00      1

[252302 rows x 3 columns]

## Shape

In [58]:
print "Original Dataset: ", dataset_original.shape
fvr = filtered_void_rows.shape
print "Filtered void rows: ", fvr
flr = filtered_less_rows.shape
print "Filtered less rows:", flr
print "Rows difference: ", fvr[0] - flr[0]

Original Dataset:  (263687, 20)
Filtered void rows:  (263459, 3)
Filtered less rows: (252302, 3)
Rows difference:  11157

## Raname column

In [83]:
rename_dataset = filtered_less_rows.rename(columns={"Material": "CÓDIGO"})
print rename_dataset

            CÓDIGO            Date  Units
0       146124-VQD   9/1/2017 0:00      1
1       662009-ZQH   9/1/2017 0:00      1
2       990552-HCP   9/1/2017 0:00      1
3       990552-HCP   9/1/2017 0:00      1
4       990552-HCP   9/1/2017 0:00     -1
5       990552-HCP   9/1/2017 0:00      1
6       990552-HCP   9/1/2017 0:00      1
7       990552-HCP   9/1/2017 0:00      1
8       662014-IQQ   9/1/2017 0:00      1
9       327277-NNV   9/1/2017 0:00      1
10      659994-MAU   9/1/2017 0:00     -1
11      659994-MAU   9/1/2017 0:00      1
12      212577-XEF   9/1/2017 0:00      1
15      212577-XEF   9/1/2017 0:00      1
16      212577-XEF   9/1/2017 0:00     -2
17      212577-XEF   9/1/2017 0:00      1
18      212577-XEF   9/1/2017 0:00      1
19      212577-XEF   9/1/2017 0:00      1
20      212577-XEF   9/1/2017 0:00      1
21      212577-XEF   9/1/2017 0:00     -1
22      163605-LET   9/1/2017 0:00      1
23      660689-PGX   9/1/2017 0:00     -1
24      660689-PGX   9/1/2017 0:00      1
25      660689-PGX   9/1/2017 0:00      1
26      760862-QGY   9/1/2017 0:00     -1
27      163518-KCS   9/1/2017 0:00      1
28      163518-KCS   9/1/2017 0:00      1
29      163518-KCS   9/1/2017 0:00      1
30      163518-KCS   9/1/2017 0:00      1
31      453195-LCT   9/1/2017 0:00      1
...            ...             ...    ...
263657  661984-GQO  9/30/2018 0:00      1
263658  661984-GQO  9/30/2018 0:00      1
263659  661984-GQO  9/30/2018 0:00      1
263660  762578-QRY  9/30/2018 0:00      1
263661  215577-STA  9/30/2018 0:00      1
263662  454287-YNG  9/30/2018 0:00      1
263663  994341-ATI  9/30/2018 0:00      1
263664  994341-ATI  9/30/2018 0:00      1
263665  146194-BTJ  9/30/2018 0:00      1
263666  573867-VWD  9/30/2018 0:00      1
263667  573867-VWD  9/30/2018 0:00      1
263668  572999-XRF  9/30/2018 0:00      1
263669  662089-NRV  9/30/2018 0:00      1
263670  215145-ARI  9/30/2018 0:00      1
263671  215145-ARI  9/30/2018 0:00      1
263672  662114-GRO  9/30/2018 0:00      1
263673  662114-GRO  9/30/2018 0:00      1
263674  573048-IRQ  9/30/2018 0:00      1
263675  573048-IRQ  9/30/2018 0:00      1
263676  573048-IRQ  9/30/2018 0:00      1
263677  573048-IRQ  9/30/2018 0:00      1
263678  573048-IRQ  9/30/2018 0:00      1
263679  573202-YSG  9/30/2018 0:00      1
263680  573657-LUT  9/30/2018 0:00      1
263681  662699-TWB  9/30/2018 0:00      1
263682  662829-TXB  9/30/2018 0:00      1
263683  164064-KKS  9/30/2018 0:00      1
263684  327345-HOP  9/30/2018 0:00      1
263685  164436-IOQ  9/30/2018 0:00      1
263686  164436-IOQ  9/30/2018 0:00      1

[252302 rows x 3 columns]

In [115]:
#print rename_dataset.groupby('CÓDIGO').Units.sum()
#print rename_dataset.groupby('Date').Units.sum().groupby('CÓDIGO')
#group = rename_dataset.groupby(['CÓDIGO', 'Date'],as_index=False)['Units'].sum()
group['year'] = pd.DatetimeIndex(group['Date']).year
group['month'] = pd.DatetimeIndex(group['Date']).month
print group

#group = rename_dataset.groupby(['CÓDIGO', 'Date'],as_index=False)['Units'].sum()

#print group

            CÓDIGO             Date  Units  year  month
0       145697-AAI   9/15/2018 0:00     -1  2018      9
1       145698-JAR    9/3/2018 0:00      1  2018      9
2       145699-SAA   8/17/2018 0:00      2  2018      8
3       145699-SAA   8/18/2018 0:00      1  2018      8
4       145699-SAA   8/19/2018 0:00      2  2018      8
5       145699-SAA   8/20/2018 0:00      1  2018      8
6       145699-SAA   8/22/2018 0:00      1  2018      8
7       145699-SAA   8/26/2018 0:00      1  2018      8
8       145699-SAA   9/22/2018 0:00      1  2018      9
9       145700-BAJ   1/18/2018 0:00      2  2018      1
10      145700-BAJ   1/19/2018 0:00      2  2018      1
11      145700-BAJ   1/20/2018 0:00     24  2018      1
12      145700-BAJ   1/21/2018 0:00     17  2018      1
13      145700-BAJ   1/22/2018 0:00     23  2018      1
14      145700-BAJ   1/23/2018 0:00      2  2018      1
15      145700-BAJ   1/24/2018 0:00      2  2018      1
16      145700-BAJ   1/26/2018 0:00      1  2018      1
17      145700-BAJ   1/30/2018 0:00      1  2018      1
18      145700-BAJ   3/10/2018 0:00      1  2018      3
19      145700-BAJ    3/9/2018 0:00      1  2018      3
20      145701-KAS  11/17/2017 0:00      1  2017     11
21      145702-TAB  10/18/2017 0:00      1  2017     10
22      145702-TAB  10/21/2017 0:00      1  2017     10
23      145702-TAB  10/27/2017 0:00      1  2017     10
24      145702-TAB   10/7/2017 0:00      1  2017     10
25      145702-TAB  11/10/2017 0:00      1  2017     11
26      145702-TAB  11/18/2017 0:00      2  2017     11
27      145702-TAB   11/8/2017 0:00      1  2017     11
28      145703-CAK  10/10/2017 0:00      1  2017     10
29      145703-CAK  11/10/2017 0:00      1  2017     11
...            ...              ...    ...   ...    ...
125006    PDIO-001   9/12/2017 0:00      0  2017      9
125007    PDIO-001   9/14/2017 0:00      0  2017      9
125008    PDIO-001   9/15/2018 0:00      0  2018      9
125009    PDIO-001   9/18/2018 0:00      0  2018      9
125010    PDIO-001    9/2/2017 0:00      0  2017      9
125011    PDIO-001    9/4/2018 0:00      0  2018      9
125012    PDIO-001    9/5/2017 0:00      0  2017      9
125013    PDIO-001    9/7/2018 0:00      0  2018      9
125014    PDIO-002   1/17/2018 0:00      0  2018      1
125015    PDIO-002    1/2/2018 0:00      0  2018      1
125016    PDIO-002  12/11/2017 0:00      0  2017     12
125017    PDIO-002  12/20/2017 0:00      0  2017     12
125018    PDIO-002  12/21/2017 0:00      0  2017     12
125019    PDIO-002   12/5/2017 0:00      0  2017     12
125020    PDIO-002   2/10/2018 0:00      0  2018      2
125021    PDIO-002    2/7/2018 0:00      0  2018      2
125022    PDIO-002   3/27/2018 0:00      0  2018      3
125023    PDIO-002    3/7/2018 0:00      0  2018      3
125024    PDIO-002   4/10/2018 0:00      0  2018      4
125025    PDIO-002   4/11/2018 0:00      0  2018      4
125026    PDIO-002    4/4/2018 0:00      0  2018      4
125027    PDIO-002   5/10/2018 0:00      0  2018      5
125028    PDIO-002   5/16/2018 0:00      0  2018      5
125029    PDIO-002   5/23/2018 0:00      0  2018      5
125030    PDIO-002    5/8/2018 0:00      0  2018      5
125031    PDIO-002   6/13/2018 0:00      0  2018      6
125032    PDIO-002    7/1/2018 0:00      0  2018      7
125033    PDIO-002   7/10/2018 0:00      0  2018      7
125034    PDIO-002    9/1/2018 0:00      0  2018      9
125035    PDIO-002   9/25/2018 0:00      0  2018      9

[125036 rows x 5 columns]

In [125]:
g = group.groupby(['CÓDIGO', (group.year),(group.month)], as_index=False).sum()
print g

           CÓDIGO  year  month  Units
0      145697-AAI  2018      9     -1
1      145698-JAR  2018      9      1
2      145699-SAA  2018      8      8
3      145699-SAA  2018      9      1
4      145700-BAJ  2018      1     74
5      145700-BAJ  2018      3      2
6      145701-KAS  2017     11      1
7      145702-TAB  2017     10      4
8      145702-TAB  2017     11      4
9      145703-CAK  2017     10      1
10     145703-CAK  2017     11      5
11     145703-CAK  2017     12      1
12     145703-CAK  2018      7      2
13     145704-LAT  2018      2     55
14     145704-LAT  2018      3     30
15     145704-LAT  2018      4      8
16     145704-LAT  2018      5      1
17     145704-LAT  2018      6      3
18     145704-LAT  2018      7      4
19     145705-UAC  2017      9      1
20     145706-DAL  2017     11     22
21     145707-MAU  2017      9     16
22     145707-MAU  2017     10      9
23     145707-MAU  2017     11     23
24     145707-MAU  2017     12      2
25     145708-VAD  2017     12      1
26     145708-VAD  2018      1      1
27     145709-EAM  2018      9      1
28     145710-NAV  2017      9      1
29     145710-NAV  2017     10      1
...           ...   ...    ...    ...
22856  995862-NZV  2018      4      4
22857  995862-NZV  2018      5      2
22858  995871-WZE  2018      1     18
22859  995871-WZE  2018      2     44
22860  995871-WZE  2018      9     57
22861  995880-FZN  2018      7      1
22862  995880-FZN  2018      8      2
22863  995880-FZN  2018      9      2
22864    PDIO-001  2017      9      0
22865    PDIO-001  2017     10      0
22866    PDIO-001  2017     11      0
22867    PDIO-001  2017     12      0
22868    PDIO-001  2018      1      0
22869    PDIO-001  2018      2      0
22870    PDIO-001  2018      3      0
22871    PDIO-001  2018      4      0
22872    PDIO-001  2018      5      0
22873    PDIO-001  2018      6      0
22874    PDIO-001  2018      7      0
22875    PDIO-001  2018      8      0
22876    PDIO-001  2018      9      0
22877    PDIO-002  2017     12      0
22878    PDIO-002  2018      1      0
22879    PDIO-002  2018      2      0
22880    PDIO-002  2018      3      0
22881    PDIO-002  2018      4      0
22882    PDIO-002  2018      5      0
22883    PDIO-002  2018      6      0
22884    PDIO-002  2018      7      0
22885    PDIO-002  2018      9      0

[22886 rows x 4 columns]

In [126]:
g.pivot(index='CÓDIGO', columns='month', values='Units')

ValueError: Index contains duplicate entries, cannot reshape